name: 02-workflow-events
on: 
  push:
  pull_request:
  schedule: 
    - cron: '0/5 * * * *'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: showing the trigger
        run: echo "I have been triggered by ${{github.event_name}} event."

