name: 04-using-actions,yaml
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    defaults: 
      working-directory: 04-actions/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls

