name: 04-activity-types,yaml
on: 
  pull_request:
    type:
      - opened
      - synchronize
    branches:
      - main
jobs: 
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Demo
        run: echo "running whenever a PR is created"
