name: using function
on: 
   pull_request:
   workflow_dispatch:
jobs:
   echo1:
      runs-on: ubuntu-latest
      steps:
         - name: Failing-step
           run: | 
              exit 1
         - name: I will be skipped
           if: success()
           run: echo "I will print if previous step succeed"

         - name: I will execute
           if: failure()
           run: echo "I will run if any previous step failed"

         - name: I will execute
           if: ${{ !cancelled() }}
           run: echo "I will execute if not cancelled"

         - name: I will execute
           if: ${{ cancelled() }}
           run: echo "I will execute if cancelled"
           

      
