name: Conditions Workflow
on: 
   workflow_dispatch:
      inputs:
         pass_unit_test:
            type: boolean
            required: false
            description: Whether unit test will pass.
            default: true

jobs:
   lint-build:
      runs-on: ubuntu-latest
      steps:
      - name: Linting and building
        run: echo "Running linting and building"
   unit-test:
      runs-on: ubuntu-latest
      steps:
      - name: Unit Test
        run: echo "Running unit test"
      - name: Failing Test
        if: ${{ !inputs.pass_unit_test }}
        run: exit 1
   deploy-nonprod:
      runs-on: ubuntu-latest
      needs: 
         - lint-build
         - unit-test
      steps:
      - name: Deploy to non prod
        run: echo "Deploying to nonprod"
   e2e-tests:
      runs-on: ubuntu-latest
      needs: deploy-nonprod
      steps:
         - name: doing E2e tests
           run: echo "Doing E2E tests"
   load-tests:
      needs: deploy-nonprod
      runs-on: ubuntu-latest
      steps:
         - name: Load tests
           run: echo "Doing Load tests"
   deploy-prod:
      runs-on: ubuntu-latest
      needs: 
         - e2e-tests
         - load-tests
      steps:
         - name: Deploy Prod
           run: echo "Deploy to Prod"
   
